import {
  Platform,
  StyleSheet,
  Text,
  View,
  StatusBar as sBar,
  TextInput,
  TouchableOpacity,
, Dimensions } from 'react-native';


const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  containerLogin: {
    flex: 0,
    height: windowHeight + sBar.currentHeight,
    width: windowWidth,
    backgroundColor: '#f2d9e6',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    paddingLeft: '8.5%',
    paddingRight: '8.5%',
    paddingTop: Platform.OS === 'android' ? sBar.currentHeight : 0,
  },
  containerRegform: {
    flex: 0,
    height: windowHeight + sBar.currentHeight,
    width: windowWidth,
    backgroundColor: '#19BB53',
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    paddingLeft: '8.5%',
    paddingRight: '8.5%',
    paddingTop: Platform.OS === 'android' ? sBar.currentHeight : 0,
  },
  circle1: {
    position: 'absolute',
    width: 382.49 + 50,
    height: 382.49 + 50,
    left: -156.65,
    top: -300.62,
    borderRadius: 382.49 + 50,
    backgroundColor: '#0582CA',
  },
  circle2: {
    position: 'absolute',
    width: 673 + 50,
    height: 673 + 50,
    left: -177,
    top: -416,
    borderRadius: 673 + 50,
    backgroundColor: '#541E5C',
  },
  circle3: {
    position: 'absolute',
    width: 382 + 50,
    height: 382 + 50,
    left: 226,
    top: -35,
    borderRadius: 382 + 50,
    backgroundColor: '#19BB53',
  },
  circle4: {
    position: 'absolute',
    width: 672.72 + 50,
    height: 672.72 + 50,
    left: -297.92,
    top: -457.01,
    borderRadius: 672.72 + 50,
    backgroundColor: '#541E5C',
  },
  circle5: {
    position: 'absolute',
    width: 441.11 + 50,
    height: 382.49 + 50,
    left: 148 + 30,
    top: 556.43 + 95,
    borderRadius: 382.49 + 50,
    backgroundColor: '#F2E0F5',
  },
  headerLogin: {
    flex: 1,
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 60,
    lineHeight: 60,
    color: '#F2E0F5',
    marginTop: windowHeight / 7.25,
    /* paddingBottom: 10,
      marginBottom: 40,
      borderBottomColor: '#5a008c',
      borderBottomWidth: 1, */
  },
  headerRegform: {
    flex: 1,
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 65,
    lineHeight: 65,
    color: '#F2E0F5',
    marginTop: windowHeight / 16.25,
    /* paddingBottom: 10,
        marginBottom: 40,
        borderBottomColor: '#5a008c',
        borderBottomWidth: 1, */
  },
  textinputLogin: {
    alignSelf: 'stretch',
    height: '8%',
    width: '100%',
    paddingLeft: 30,
    paddingRight: 30,
    // marginLeft: '2.5%',
    // marginRight: '2.5%',
    backgroundColor: '#e4b4cd',
    borderRadius: 20,
    borderColor: 'transparent',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 100,
    color: '#3C3C3C',
    marginBottom: 20,
    /* color: '#000000',
      borderBottomColor: '#5a008c',
      borderBottomWidth: 1, */
  },
  textinputRegform: {
    alignSelf: 'stretch',
    height: '8%',
    width: '100%',
    paddingLeft: 30,
    paddingRight: 30,
    // marginLeft: '2.5%',
    // marginRight: '2.5%',
    backgroundColor: '#199353',
    borderRadius: 20,
    borderColor: 'transparent',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 100,
    color: '#3C3C3C',
    marginBottom: 20,
    /* color: '#000000',
        borderBottomColor: '#5a008c',
        borderBottomWidth: 1, */
  },
  direction: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  midTxt: {
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 40,
    lineHeight: 40,
    color: '#242528',
    marginTop: 12.75,
  },
  midBtn: {
    borderRadius: 100,
    width: 8.5,
    height: 8.5,
    backgroundColor: '#4D525A',
    padding: 35,
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginBottom: 20,
    /* alignSelf: 'stretch',
      alignItems: 'center',
      padding: 20,
      marginTop: 30, */
  },
  btnFbGoogleLogin: {
    height: '6.20%',
    width: '100%',
    // marginLeft: '8.5%',
    // marginRight: '8.5%',
    backgroundColor: '#45194d',
    borderColor: '#E15A97',
    borderRadius: 10,
    marginBottom: 10,
  },
  btnFbGoogleRegform: {
    height: '6.20%',
    width: '100%',
    // marginLeft: '8.5%',
    // marginRight: '8.5%',
    backgroundColor: '#e4b4cd',
    borderColor: '#0582CA',
    borderRadius: 10,
    marginBottom: 10,
  },
  txtBtnFbGoogleLogin: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: '#F2E0F5',
    marginTop: '3%',
  },
  txtBtnFbGoogleRegform: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: '#38143E',
    marginTop: '3%',
  },
  txtBtnOthersLogin: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 18,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: '#242528',
    marginBottom: 40,
  },
  txtBtnOthersRegform: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 18,
    alignSelf: 'flex-end',
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: '#242528',
    marginBottom: 40,
  },
});

export default styles;
