import {
  Platform,
  StyleSheet,
  StatusBar as sBar,
  Dimensions,
} from 'react-native';
import { gray, green, highlight, purple } from '../../theme/colorPalette';

const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  containerLogin: {
    flex: 0,
    height: windowHeight + sBar.currentHeight,
    width: windowWidth,
    backgroundColor: purple.frenchLilacMedium(),
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    paddingLeft: '8.5%',
    paddingRight: '8.5%',
    paddingTop: Platform.OS === 'android' ? sBar.currentHeight : 0,
  },
  containerRegform: {
    flex: 0,
    height: windowHeight + sBar.currentHeight,
    width: windowWidth,
    backgroundColor: green.mountainMeadow(),
    alignItems: 'stretch',
    justifyContent: 'flex-end',
    paddingLeft: '8.5%',
    paddingRight: '8.5%',
    paddingTop: Platform.OS === 'android' ? sBar.currentHeight : 0,
  },
  circle1: {
    position: 'absolute',
    width: 382.49 + 50,
    height: 382.49 + 50,
    left: -156.65,
    top: -300.62,
    borderRadius: 382.49 + 50,
    backgroundColor: highlight.lochmara(),
  },
  circle2: {
    position: 'absolute',
    width: 673 + 50,
    height: 673 + 50,
    left: -177,
    top: -416,
    borderRadius: 673 + 50,
    backgroundColor: purple.honeyFlower(),
  },
  circle3: {
    position: 'absolute',
    width: 382 + 50,
    height: 382 + 50,
    left: 226,
    top: -35,
    borderRadius: 382 + 50,
    backgroundColor: green.mountainMeadow(),
  },
  circle4: {
    position: 'absolute',
    width: 672.72 + 50,
    height: 672.72 + 50,
    left: -297.92,
    top: -457.01,
    borderRadius: 672.72 + 50,
    backgroundColor: purple.honeyFlower(),
  },
  circle5: {
    position: 'absolute',
    width: 441.11 + 50,
    height: 382.49 + 50,
    left: 148 + 30,
    top: 556.43 + 95,
    borderRadius: 382.49 + 50,
    backgroundColor: purple.frenchLilacLighter(),
  },
  headerLogin: {
    flex: 1,
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 60,
    lineHeight: 60,
    color: purple.frenchLilacLighter(),
    marginTop: windowHeight / 7.25,
    /* paddingBottom: 10,
        marginBottom: 40,
        borderBottomColor: purple.honeyFlower(),
        borderBottomWidth: 1, */
  },
  headerRegform: {
    flex: 1,
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 65,
    lineHeight: 65,
    color: purple.frenchLilacLighter(),
    marginTop: windowHeight / 16.25,
    /* paddingBottom: 10,
          marginBottom: 40,
          borderBottomColor: purple.honeyFlower(),
          borderBottomWidth: 1, */
  },
  textinputLogin: {
    alignSelf: 'stretch',
    height: '8%',
    width: '100%',
    paddingLeft: 30,
    paddingRight: 30,
    // marginLeft: '2.5%',
    // marginRight: '2.5%',
    backgroundColor: purple.lightWisteriaLighter(),
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: purple.honeyFlower(),
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 15,
    color: gray.shark(),
    marginBottom: 20,
    /* color: gray.darkest(),
        borderBottomColor: purple.honeyFlower(),
        borderBottomWidth: 1, */
  },
  textinputRegform: {
    alignSelf: 'stretch',
    height: '8%',
    width: '100%',
    paddingLeft: 30,
    paddingRight: 30,
    // marginLeft: '2.5%',
    // marginRight: '2.5%',
    backgroundColor: green.salem(),
    borderRadius: 20,
    borderColor: 'transparent',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 15,
    color: gray.outerSpace(),
    marginBottom: 20,
    /* color: gray.darkest(),
          borderBottomColor: purple.honeyFlower(),
          borderBottomWidth: 1, */
  },
  direction: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  midTxt: {
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 40,
    lineHeight: 40,
    color: gray.shark(),
    marginTop: 12.75,
  },
  midBtn: {
    borderRadius: 100,
    width: 8.5,
    height: 8.5,
    backgroundColor: gray.abbey(),
    padding: 35,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    marginBottom: 20,
    /* alignSelf: 'stretch',
        alignItems: 'center',
        padding: 20,
        marginTop: 30, */
  },
  arrow: {
    position: 'absolute',
  },
  viewbtnFbGoogle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnFbGoogleLogin: {
    height: '6.20%',
    width: '100%',
    justifyContent: 'center',
    // marginLeft: '8.5%',
    // marginRight: '8.5%',
    backgroundColor: purple.grapeDark(),
    borderColor: highlight.cranberry(),
    borderRadius: 10,
    marginBottom: 10,
  },
  btnFbGoogleRegform: {
    height: '6.20%',
    width: '100%',
    // marginLeft: '8.5%',
    // marginRight: '8.5%',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: purple.lightWisteriaLighter(),
    borderColor: highlight.lochmara(),
    borderRadius: 10,
    marginBottom: 10,
  },
  iconBtnFbGoogle: {
    paddingLeft: '7.5%',
    paddingRight: '12.5%',
  },
  txtBtnFbGoogleLogin: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: purple.frenchLilacLighter(),
  },
  txtBtnFbGoogleRegform: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: purple.grapeDark(),
  },
  txtBtnOthersLogin: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 18,
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: gray.shark(),
    marginBottom: 40,
  },
  txtBtnOthersRegform: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 18,
    alignSelf: 'flex-end',
    // lineHeight: 171,
    textAlign: 'center',
    letterSpacing: 0.1,
    color: gray.iron(),
    marginBottom: 40,
  },
  btnButtonLogoutDelete: {
    backgroundColor: gray.iron(),
    width: windowWidth / 2.5,
    height: windowHeight / 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  txtBtnDeleteLogout: {
    fontSize: 12,
    textAlign: 'center',
  },
});

export default styles;
